// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LungoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void lungo() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.cssSelector("li:nth-child(2) span:nth-child(2)")).click();
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("davis");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".active span:nth-child(2)")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) span:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".xd-container")).click();
    driver.findElement(By.id("search-owner-form")).click();
    driver.findElement(By.id("search-owner-form")).click();
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("davis");
    driver.findElement(By.id("lastName")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Harold Davis")).click();
    driver.findElement(By.cssSelector(".active span:nth-child(2)")).click();
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("davis");
    driver.findElement(By.id("lastName")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Betty Davis")).click();
    driver.findElement(By.cssSelector(".active span:nth-child(2)")).click();
  }
}
